/* eslint-disable */
export const SET_STEPOFLEFT = 'SET_STEPOFLEFT';
export const SET_STEPOFBOTTOM = 'SET_STEPOFBOTTOM';
export const SET_STEPOFLEFT1 = 'SET_STEPOFLEFT1';
export const NATURAL = 'NATURAL';
export const SET_RISKLEVEL = 'SET_RISKLEVEL';
export const SET_BOTTOMFLAG = 'SET_BOTTOMFLAG';
export const SET_PRIMARYRISKSOURCE = 'SET_PRIMARYRISKSOURCE';
export const SET_SEFETYRISKSOURCE = 'SET_SEFETYRISKSOURCE';
export const SET_TEAMSTATISTICS = 'SET_TEAMSTATISTICS';
export const SET_SHELTERSHPSTATISTICS = 'SET_SHELTERSHPSTATISTICS';
export const SET_STEPNAME = 'SET_STEPNAME';
