/* eslint-disable */
const state = {
  leftFlag: 0,
  stepName: {
    name: ''
  },
  leftInfo: [
    { timename: '化工危化(个)' },
    { timename: '非煤矿山(个)' },
    { timename: '烟花爆竹(个)' },
    { timename: '自然灾害(个)' },
    { timename: '道路运输(个)' },
    { timename: '建设工程(个)' },
    { timename: '密集场所(个)' },
    { timename: '山塘易涝积水(个)' },
    { timename: '山塘易涝积水(个)' },
  ],
  leftInfo1:[],
  coordinate:[],
  bottomFlag: 0,
  bottomInfo: {
    title:{titlename:"化工危化",titlenum:"250"},
    content:[
    { list_name: '生产企业', list_num: '111' },
    { list_name: '仓储经营', list_num: '11' },
    { list_name: '加油站', list_num: '11' },
    { list_name: '使用企业', list_num: '11' },
    { list_name: '带存储经营', list_num: '11' },
  ]
},
bottomInfo1:[],
  point:[],
  point0:  [
    { point_num: '2345' },
    { point_num: '2345' },
    { point_num: '2345' },
    { point_num: '2345' },
    { point_num: '2345' },
    { point_num: '2345' },
    { point_num: '2345' },
    { point_num: '2345' },
    { point_num: '2345' },
    { point_num: '2345' },
    { point_num: '2345' },
    { point_num: '2345' }
  ],
  point00:  [
    { point_num: '2345' },
    { point_num: '2345' },
    { point_num: '2345' },
    { point_num: '2345' },
    { point_num: '2345' },
    { point_num: '2345' },
    { point_num: '2345' },
    { point_num: '2345' },
    { point_num: '2345' },
    { point_num: '2345' },
    { point_num: '2345' },
    { point_num: '2345' }
  ],
  btn:0,
  natural: { 'top': 580, 'bot': 265 },
  risklevel:{},
  TeamStatistics:[],
  TeamTotal:"0",
  PointTotal:"0",
  PointTotal0:"0",
  SheltershpStatistics:[],
  SheltershpTotal:"0",
  SaveReserve:[{ list_name: '棉被', list_num: '1365条' },
  { list_name: '棉被', list_num: '1236床' },
  { list_name: '草席', list_num: '471件' },
  { list_name: '毛巾被', list_num: '2658床' },
  { list_name: '雨鞋', list_num: '2255双' },
  { list_name: '雨衣', list_num: '1365条' },
  { list_name: '行军床', list_num: '1236床' },
  { list_name: '凉席', list_num: '471件' },
  { list_name: '雨伞', list_num: '2658个' },
  { list_name: '垫子', list_num: '1122个' },
  { list_name: '毛巾', list_num: '1365条' },
  { list_name: '毛毯', list_num: '1236条' },
  { list_name: '女单衣', list_num: '471件' },
  { list_name: '脸盆', list_num: '2658个' },
  { list_name: '袜子', list_num: '11' },
  { list_name: '空调被', list_num: '1365条' },
  { list_name: '防潮垫', list_num: '1236张' },],
  SaveReserve1:[{ list_name: '夹板', list_num: '1365个' },
  { list_name: '帐篷', list_num: '1236个' },
  { list_name: '生活应急包', list_num: '471个' },
  { list_name: '医疗包', list_num: '2658个' },
  { list_name: '睡袋', list_num: '2255个' },
  { list_name: '灭火器', list_num: '1365个' },
  { list_name: '应急箱', list_num: '1236个' },
  { list_name: '蜡烛', list_num: '471个' },
  { list_name: '急救箱', list_num: '2658个' },
  { list_name: '蜡烛', list_num: '1122个' },
  { list_name: '消毒液', list_num: '1365个' },
  { list_name: '应急箱', list_num: '1236箱' },
  { list_name: '篷布', list_num: '471个' },
  { list_name: '综合急救箱', list_num: '2658箱' },],
  SaveReserve2:[{ list_name: '土工布', list_num: '6190平方米' },
  { list_name: '石料', list_num: '1236立方米' },
  { list_name: '铅丝', list_num: '471卷' },
  { list_name: '货架', list_num: '2658个' },
  { list_name: '铅丝', list_num: '2255圈' },
  { list_name: '木材', list_num: '1365米' },
  { list_name: '储水桶', list_num: '126个' },
  { list_name: '无纺布', list_num: '471米' },
  { list_name: '桩木', list_num: '2658立方米' },
  { list_name: '网笼', list_num: '1122只' },
  { list_name: '红袖标', list_num: '136530条' },
  { list_name: '铅丝', list_num: '123米' },]
}
export default state
